### ISSUE TITLE
TYPEERROR when running ./yt-subs.sh and outdated README.

### ISSUE THREAD

**Issue by FarazzShaikh** [SPDUK/youtube-subscription-dl#16]
Outdated Readme
---
The `Turn on the YouTube Data API (free, 10,000 queries/day)` section of the README states - 
```
Select the application type Other, enter the name "YouTube Data API Quickstart", and click the Create button.
```
However, the Google API Add Credentials page does not show the option for the Application type of _Other_. We now must use the type _Web Application_ and add an **Authorized redirect URI** manually.

TYPEERROR when running ./yt-subs.sh
---
Running `./yt-subs.sh` out of the box gives -

```
/Users/currentUser/Documents/youtube-subscription-dl/src/index.js:52
  const clientSecret = credentials.installed.client_secret;
                                             ^

TypeError: Cannot read property 'client_secret' of undefined
...
```
This is because the new **_client_secret.json_** file downloaded form Google API Credentials page, uses the key "_web_" in place of "_installed_".

**Will Post PR with changes,** great work by the way ✌️

**Comment by SPDUK** [comment]
@FarazzShaikh Thanks for this :+1:
